### ISSUE TITLE
TypeError: Cannot read property 'latencies' of undefined

### ISSUE THREAD

**Issue by countergram** [Nordstrom/artillery-plugin-cloudwatch#5]
cloudwatch.js line 81: `latencies = report.aggregate.latencies`

It appears that `report.latencies` exists but `aggregate` does not.

**Comment by erikerikson** [comment]
We've gotta stop meeting this way ;P . Thanks for the report.

Sorry you hit this.  This plugin has been a little abandoned.  That smells of a shift in artillery or a less than 10 second phase.

Something else you may hit is a rate limiting error due to a lack of implementation for #3 and the need to expediently offload the data prior to completion.  Another issue is #4, we have resolved these matters in https://github.com/Nordstrom/artillery-plugin-influxdb but this one has languished.

Particularly because CloudWatch has improved since this was written, we have incentive to try and prioritize greater productization of this plugin.  @ashmibhanushali

**Comment by countergram** [comment]
It's not related to length over or under 10sec. Looks like the plugin interface may have changed and `aggregate` is no longer a property. I'm also having some issues with the putMetricData call not finishing which is making it harder to patch.

**Comment by erikerikson** [comment]
Here is the fix we made in another plugin for this:
https://github.com/Nordstrom/artillery-plugin-influxdb/commit/b9a0c3d82f242ba95adc5d6fb5842eccff9de11d

I'll port that here shortly.

**Comment by erikerikson** [comment]
Sorry for the delay.

**Comment by erikerikson** [comment]
Regarding the failure of putMetricData not finishing, that can result from over calling to the CloudWatch API and being slowed down + rate limited.  This was resolved in the influx plugin by changing to reporting on the intermediate results.  When this was written doing that would lose data but we submitted a fix to resolve that between then and now.

**Comment by erikerikson** [comment]
This PR should resolve both of your issues but I haven't yet tested it.  Busy day.

**Comment by erikerikson** [comment]
https://github.com/Nordstrom/artillery-plugin-cloudwatch/pull/7 should resolve both of your issues but I haven't yet tested it.  Busy day.

**Comment by erikerikson** [comment]
@countergram we have published v0.0.2 to npm.  please check it out and hopefully report your success.  Thank you.!

**Comment by erikerikson** [comment]
going to close this out as fixed.  please re-open it if there continues to be an issue.
